stages:
  - hello_world

image: "rust:1.57.0"

# Optional: Install a C compiler, cmake and git into the container.
# You will often need this when you (or any of your dependencies) depends on C code.
before_script:
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential

report_toolchain_versions:
  stage: hello_world
  script:
  - rustc --version && cargo --version  # Print version info for debugging

cargo_fmt:
  stage: hello_world
  script:
    - cargo fmt --release --workspace --verbose

cargo_check:
  stage: hello_world
  script:
    - cargo check --release --workspace --verbose

cargo_clippy:
  stage: hello_world
  dependencies:
    - cargo_check
  script:
    - cargo clippy --release --workspace --verbose

cargo_build:
  stage: hello_world
  dependencies:
    - cargo_clippy
  script:
    - cargo build --release --workspace --verbose

cargo_test:
  stage: hello_world
  dependencies:
    - cargo_build
  script:
    - cargo test --release --workspace --verbose

sast:
  stage: hello_world

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
