stages:
  - build_stage
  - test_stage

image: "rust:1.57.0"

# Optional: Install a C compiler, cmake and git into the container.
# You will often need this when you (or any of your dependencies) depends on C code.
before_script:
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential

toolchain_versions_job:
  stage: build_stage
  script:
  - rustc --version && cargo --version  # Print version info for debugging

build_job:
  stage: build_stage
  script:
  - cargo build --workspace --verbose

test_job:
  stage: test_stage
  dependencies:
    - build_job
  script:
    - cargo test --workspace --verbose

sast:
  stage: test_stage

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
